### ISSUE TITLE
Panic on mouseover

### ISSUE THREAD

**Issue by zesterer** [shivshank/mini_gl_fb#4]
```
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/zesterer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When using the setup in the README example.

**Comment by LoganDark** [comment]
@zesterer Please confirm if the issue is still present. I have tested multi_window on x11 and it seems to work correctly. Glutin (and by extension winit) has been updated massively.

If it still causes an issue, please provide me with your distribution, distro version, version of xorg (x11), desktop environment/window manager, etc. and I will attempt to reproduce.

**Comment by zesterer** [comment]
@LoganDark I can confirm that this issue still exists on `0.7.0`.

You can see it when running any of the examples from the `refactor` on https://www.github.com/zesterer/euc branch (requires nightly).

My desktop environment is Budgie on Arch Linux.

My xorg version is:

```
X.Org X Server 1.20.10
X Protocol Version 11, Revision 0
```

**Comment by LoganDark** [comment]
> @LoganDark I can confirm that this issue still exists on `0.7.0`.

I'm talking about `0.8.0`, which is the huge overhaul I did in #5.

> You can see it when running any of the examples from the `refactor` on https://www.github.com/zesterer/euc branch (requires nightly).
> 
> My desktop environment is Budgie on Arch Linux.
> 
> My xorg version is:
> 
> ```
> X.Org X Server 1.20.10
> X Protocol Version 11, Revision 0
> ```

I'll set it up in a VM and see if I can reproduce.

**Comment by LoganDark** [comment]
Welp, looks like no VM for me. I got Arch up and running, but running `startx` with `.xinitrc` set to run `exec budgie-desktop` causes this:

![image](https://user-images.githubusercontent.com/4723091/105530777-24166380-5c9d-11eb-9d06-216646db5a11.png)

(Also, my mouse isn't recognized; Budgie/GNOME/whatever thinks it's some dumb accessibility thing, so it doesn't show a cursor and moving it just causes the keyboard focus to move around.)

I'll need you to perform more debugging steps on your end. Can you please try to get a backtrace? We need to know where this is in mini_gl_fb. Also, using a debugger (like CLion's) to find out what line of `mini_gl_fb` is causing the panic could also be useful.

I also have X11 on Arch, but `mini_gl_fb` worked flawlessly for me, as you can see in the new readme (all three screenshots were taken by me).

**Comment by LoganDark** [comment]
I have successfully reproduced your issue using my local Arch install, by running the euc teapot example. Seems to not be Budgie-specific.

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/202720bf483088dbdb343f78c0aa77067fdd8156/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/202720bf483088dbdb343f78c0aa77067fdd8156/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/202720bf483088dbdb343f78c0aa77067fdd8156/library/core/src/panicking.rs:50:5
   3: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
   4: winit::platform::platform::x11::EventsLoop::process_event
   5: mini_gl_fb::core::Internal::glutin_handle_basic_input
   6: teapot::main
```

It looks like an issue caused by winit being outdated. `mini_gl_fb` `0.8.0` should fix this by updating winit. However, it's not yet published to crates.io. Bug @dxenonb for that...

**Comment by LoganDark** [comment]
Yeah, this is a problem with `winit`: https://stackoverflow.com/a/65261408
